# Make sure to check the documentation at http://goreleaser.com
builds:
  - ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - 386
    main: ./
    id: "kairos-cli"
    binary: "kairos-cli"
source:
  enabled: true
  name_template: 'kairos-cli-{{ .Tag }}-source'
archives:
  # Default template uses underscores instead of -
  - name_template: "kairos-cli-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'kairos-cli-{{ .Tag }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
