---
name: 'Test arm build'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # OIDC support
    strategy:
      fail-fast: false
      matrix:
        include:
          - flavor: "opensuse-leap-arm-rpi"
            model: rpi64
          # tumbleweed disabled until there is a new release of core images.
          # otherwise it tries to pull from quay.io/kairos/core-${FLAVOR}:${CORE_VERSION} but there is no tumbleweed with CORE_VERSION
          #- flavor: "opensuse-tumbleweed-arm-rpi"
          #  model: rpi64
          - flavor: "alpine-arm-rpi"
            model: rpi64
    steps:
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - uses: actions/checkout@v3
      - run: |
          git fetch --prune --unshallow
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Login to Quay Registry
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Build  🔧
        env:
          FLAVOR: ${{ matrix.flavor }}
          MODEL: ${{ matrix.model }}
          IMAGE: "quay.io/kairos/kairos-${{ matrix.flavor }}"
          TAG: "latest"
        run: |
          ./earthly.sh +all-arm --IMAGE_NAME=kairos-$FLAVOR-$TAG.img --IMAGE="$IMAGE:$TAG" --MODEL=$MODEL --FLAVOR=$FLAVOR
      - name: Push to quay
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          COSIGN_YES: true
          IMAGE: "quay.io/kairos/kairos-${{ matrix.flavor }}"
          TAG: "latest"
        run: |
          docker push "$IMAGE:$TAG" # Otherwise .RepoDigests will be empty for some reason
          cosign sign $(docker image inspect --format='{{index .RepoDigests 0}}' "$IMAGE:$TAG")
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.flavor }}-image
          path: build
          if-no-files-found: error
