name: Build image

on: 
 push:
   branches:
     - main
 pull_request:

concurrency:
  group: ci-image-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # OIDC support
    strategy:
      fail-fast: false
      matrix:
       k3s-version:
          - v1.24.4+k3s1
          - v1.23.10+k3s1
          - v1.22.13+k3s1
       include:
         - flavor: "opensuse"
         #- flavor: "tumbleweed"
         #- flavor: "fedora"
         - flavor: "ubuntu"
         - flavor: "alpine"
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Login to Quay Registry
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io
      - name: Build  🔧
        env:
          FLAVOR: ${{ matrix.flavor }}
          K3S_VER: ${{ matrix.k3s-version }}
          IMAGE: quay.io/c3os/c3os-${{ matrix.flavor }}:latest
        run: |
          ./earthly.sh +all --IMAGE=$IMAGE --FLAVOR=$FLAVOR --K3S_VERSION=$K3S_VER
          sudo mv build/* .
          sudo rm -rf build
      - uses: actions/upload-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.iso.zip
          path: |
            *.iso
            *.sha256
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.initrd.zip
          path: |
            *-initrd
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.squashfs.zip
          path: |
            *.squashfs
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.kernel.zip
          path: |
            *-kernel
            *-initrd
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.ipxe.zip
          path: |
            *.ipxe
          if-no-files-found: error
      - name: Push to quay
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          COSIGN_EXPERIMENTAL: 1
        run: | 
          docker push quay.io/c3os/c3os-${{ matrix.flavor }}:latest
          cosign sign quay.io/c3os/c3os-${{ matrix.flavor }}:latest
      - name: Push to testing
        run: | 
          docker tag quay.io/c3os/c3os-${{ matrix.flavor }}:latest ttl.sh/c3os-${{ matrix.flavor }}-${{ github.sha }}:8h
          docker push ttl.sh/c3os-${{ matrix.flavor }}-${{ github.sha }}:8h
# Test start
  build-vm-images:
    needs: 
    - build
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
       include:
         - flavor: "opensuse"
         - flavor: "alpine"
        # - flavor: "tumbleweed"
#         - flavor: "ubuntu"
#         - flavor: "fedora"
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          brew install hudochenkov/sshpass/sshpass
          brew install qemu
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.iso.zip
      - run: |
              git clone https://github.com/c3os-io/c3os
              ls -liah
              iso=$(ls *.iso)
              bash c3os/scripts/build_vm.sh $iso
      - uses: actions/upload-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.qcow2.tar.xz
          path: |
            *.qcow2.tar.xz
      - uses: actions/upload-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.ova
          path: |
            *.ova
          if-no-files-found: error
  prepare-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: '^1.16'
      - name: Prepare config
        run: |
              ./earthly.sh +test-create-config --WITH_DNS=true
      - uses: actions/upload-artifact@v2
        with:
          name: config.yaml
          path: |
             config.yaml
          if-no-files-found: error


  upgrade-single-node-k8s-test:
    needs: 
    - prepare-test
    - upgrade-test
    runs-on: macos-12
    strategy:
      fail-fast: true
      matrix:
       include:
         - flavor: "opensuse"
           node: "A" # Arbitrary field
         - flavor: "alpine"
           node: "B" # Arbitrary field
         #- flavor: "tumbleweed"
         #  node: "C"
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.iso.zip
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: config.yaml
      - name: Install deps
        run: |
          brew install cdrtools jq
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: '^1.16'
      - run: |
              ls -liah
              export ISO=$PWD/$(ls *.iso)
              export GOPATH="/Users/runner/go"
              export PATH=$PATH:$GOPATH/bin
              export CLOUD_INIT=$PWD/config.yaml 
              export CREATE_VM=true 
              export FLAVOR=${{ matrix.flavor }}
              ./.github/run_test.sh "upgrade-k8s"
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ matrix.flavor }}-vbox.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn

  decentralized-k8s-test-opensuse:
    needs: 
    - prepare-test
    - upgrade-single-node-k8s-test
    - upgrade-test
    runs-on: macos-12
    strategy:
      fail-fast: true
      matrix:
       include:
         - flavor: "opensuse"
           node: "A" # Arbitrary field
         - flavor: "opensuse"
           node: "B"
#         - flavor: "alpine"
#           node: "C"
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.iso.zip
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: config.yaml
      - name: Install deps
        run: |
          brew install cdrtools jq
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: '^1.16'
      - run: |
              ls -liah
              export ISO=$PWD/$(ls *.iso)
              export GOPATH="/Users/runner/go"
              export PATH=$PATH:$GOPATH/bin
              export CLOUD_INIT=$PWD/config.yaml
              export CREATE_VM=true
              export FLAVOR=${{ matrix.flavor }}
              ./.github/run_test.sh "decentralized-k8s"
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ matrix.flavor }}-vbox.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn

  prepare-alpine-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: '^1.16'
      - name: Prepare config
        run: |
              ./earthly.sh +test-create-config --WITH_DNS=true
      - uses: actions/upload-artifact@v2
        with:
          name: config.yaml
          path: |
             config.yaml
          if-no-files-found: error

  decentralized-k8s-test-alpine:
    needs: 
    - prepare-alpine-test
    - decentralized-k8s-test-opensuse
    - upgrade-test
    runs-on: macos-12
    strategy:
      fail-fast: true
      matrix:
       include:
         - flavor: "alpine"
           node: "A" # Arbitrary field
         - flavor: "alpine"
           node: "B"
#         - flavor: "alpine"
#           node: "C"
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: c3os-${{ matrix.flavor }}.iso.zip
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: config.yaml
      - name: Install deps
        run: |
          brew install cdrtools jq
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: '^1.16'
      - run: |
              ls -liah
              export ISO=$PWD/$(ls *.iso)
              export GOPATH="/Users/runner/go"
              export PATH=$PATH:$GOPATH/bin
              export CLOUD_INIT=$PWD/config.yaml
              export CREATE_VM=true
              export FLAVOR=${{ matrix.flavor }}
              ./.github/run_test.sh "decentralized-k8s"
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ matrix.flavor }}-vbox.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn

  latest-release:
    runs-on: ubuntu-latest
    steps:
    - uses: robinraju/release-downloader@v1.5
      with:     
      # A flag to set the download target as latest release
      # The default value is 'false'
        latest: true
        repository: "c3os-io/provider-c3os"
        fileName: "*.iso"
        out-file-path: "last-release"
    - uses: actions/upload-artifact@v2
      with:
          name: latest-release.zip
          path: last-release
          if-no-files-found: error

  qrcode-test-cli:
    needs: 
    - build
    - prepare-alpine-test
    - upgrade-test

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:      
          name: config.yaml
    - name: Install Go
      uses: actions/setup-go@v2
      with:
          go-version: '^1.16'
    - run: |
             ./earthly.sh +build-c3os-agent-provider
             sudo cp -rfv build/agent-provider-c3os /usr/bin/c3os
             export CLOUD_INIT=$PWD/tests/assets/qrcode.yaml
             export FLAVOR=${{ matrix.flavor }} 
             ./.github/run_test.sh "qrcode-register"
      env:
       SENDKEY: 4kgpo43kphopj
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: screenshot.zip
        path: |
          tests/*.png
  qrcode-test:
    needs: 
    - build
    - upgrade-test
    - prepare-alpine-test
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
       include:
         - flavor: "alpine"
           node: "A" # Arbitrary field
#         - flavor: "alpine"
#           node: "C"
    steps:
    - uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:      
          name: config.yaml
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
          name: c3os-${{ matrix.flavor }}.iso.zip
    - name: Install deps
      run: |
        brew install cdrtools jq
    - name: Install Go
      uses: actions/setup-go@v2
      with:
          go-version: '^1.16'
    - run: |
            ls -liah
            export ISO=$PWD/$(ls *.iso)
            export GOPATH="/Users/runner/go"
            export PATH=$PATH:$GOPATH/bin
            export CLOUD_INIT=$PWD/tests/assets/qrcode.yaml
            export CREATE_VM=true
            export FLAVOR=${{ matrix.flavor }} 
            ./.github/run_test.sh "qrcode-install"
      env:
       SENDKEY: 4kgpo43kphopj
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ${{ matrix.flavor }}-qrcode-test.logs.zip
        path: tests/**/logs/*
        if-no-files-found: warn


  upgrade-test:
    needs: 
    - build
    - latest-release
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
       include:
         - flavor: "alpine"
           node: "A" # Arbitrary field
         - flavor: "opensuse"
           node: "B"
#         - flavor: "alpine"
#           node: "C"
    steps:
    - uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: latest-release.zip
    - name: Install deps
      run: |
        brew install cdrtools jq
    - name: Install Go
      uses: actions/setup-go@v2
      with:
          go-version: '^1.16'
    - run: |
            ls -liah
            export ISO=$PWD/$(ls c3os-${{ matrix.flavor }}-*.iso | tail -n1 )
            export GOPATH="/Users/runner/go"
            export CONTAINER_IMAGE=ttl.sh/c3os-${{ matrix.flavor }}-${{ github.sha }}:8h
            export PATH=$PATH:$GOPATH/bin
            export CLOUD_INIT=$PWD/tests/assets/config.yaml
            export CREATE_VM=true
            export FLAVOR=${{ matrix.flavor }}
            ./.github/run_test.sh "upgrade-latest-with-kubernetes"
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ${{ matrix.flavor }}-upgrade-test.logs.zip
        path: tests/**/logs/*
        if-no-files-found: warn
  
