name: Lint
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  call-workflow:
    uses: kairos-io/linting-composite-action/.github/workflows/reusable-linting.yaml@main
    with:
      yamldirs: "."
